// Generated by CoffeeScript 1.10.0
var AppRegistry, Application, Component, React, ReactNative, ScrollView, StyleSheet, TabBarIOS, TaskView, Text, TextInput, TodayView, View, styles,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

React = require("react");

Component = React.Component;

ReactNative = require("react-native");

AppRegistry = ReactNative.AppRegistry, TextInput = ReactNative.TextInput, View = ReactNative.View, Text = ReactNative.Text, StyleSheet = ReactNative.StyleSheet, ScrollView = ReactNative.ScrollView, TabBarIOS = ReactNative.TabBarIOS;

TaskView = (function(superClass) {
  extend(TaskView, superClass);

  function TaskView() {
    return TaskView.__super__.constructor.apply(this, arguments);
  }

  TaskView.prototype.render = function() {
    return React.createElement(Text, {
      "style": styles.task
    }, this.props.text);
  };

  return TaskView;

})(Component);

TodayView = (function(superClass) {
  extend(TodayView, superClass);

  function TodayView(props) {
    this.updateText = bind(this.updateText, this);
    this.state = {
      text: 'Useless Multiline Placeholder',
      tasks: []
    };
  }

  TodayView.prototype.updateText = function(text) {
    return this.setState((function(_this) {
      return function(state) {
        state.tasks.push({
          text: text
        });
        return {
          text: "",
          tasks: state.tasks
        };
      };
    })(this));
  };

  TodayView.prototype.render = function() {
    var i, item, itemRenders, j, len, ref;
    itemRenders = [];
    ref = this.state.tasks;
    for (i = j = 0, len = ref.length; j < len; i = ++j) {
      item = ref[i];
      itemRenders.push(React.createElement(TaskView, {
        "key": i,
        "text": item.text
      }));
    }
    return React.createElement(ScrollView, {
      "style": styles.today
    }, itemRenders, React.createElement(TextInput, {
      "ref": 'Input',
      "style": {
        marginTop: 100,
        height: 200,
        borderColor: 'gray',
        borderWidth: 0
      },
      "onChangeText": ((function(_this) {
        return function(text) {
          return _this.setState({
            text: text
          });
        };
      })(this)),
      "onSubmitEditing": ((function(_this) {
        return function(event) {
          return _this.updateText(event.nativeEvent.text);
        };
      })(this)),
      "value": this.state.text
    }));
  };

  return TodayView;

})(Component);

Application = (function(superClass) {
  extend(Application, superClass);

  function Application(props) {
    Application.__super__.constructor.call(this, props);
    this.state = {
      selectedTab: 'today'
    };
  }

  Application.prototype.render = function() {
    return React.createElement(TabBarIOS, {
      "unselectedTintColor": "lightgray",
      "tintColor": "white",
      "barTintColor": "black"
    }, React.createElement(TabBarIOS.Item, {
      "title": "TODAY",
      "selected": this.state.selectedTab === 'today',
      "onPress": ((function(_this) {
        return function() {
          return _this.setState({
            selectedTab: 'today'
          });
        };
      })(this))
    }, React.createElement(TodayView, null)), React.createElement(TabBarIOS.Item, {
      "title": "MY LIST",
      "selected": this.state.selectedTab === 'mylist',
      "onPress": ((function(_this) {
        return function() {
          return _this.setState({
            selectedTab: 'mylist'
          });
        };
      })(this))
    }, React.createElement(View, null)), React.createElement(TabBarIOS.Item, {
      "title": "PROFILE"
    }, React.createElement(View, null)));
  };

  return Application;

})(Component);

styles = StyleSheet.create({
  heading: {
    fontSize: 42,
    textAlign: 'center',
    marginTop: 50
  },
  task: {
    fontSize: 24,
    marginTop: 15,
    marginLeft: 15,
    marginRight: 15,
    color: '#FFFFFF',
    backgroundColor: 'darkgray'
  },
  today: {
    backgroundColor: 'white'
  }
});

AppRegistry.registerComponent('MeowNowHome', function() {
  return Application;
});
