// Generated by CoffeeScript 1.10.0
var Realm, Task, realm;

Realm = require('realm');

Task = (function() {
  function Task() {}

  return Task;

})();

Task.schema = {
  name: 'Task',
  properties: {
    category: 'int',
    content: 'string',
    created: 'date',
    modified: 'date',
    done: 'bool',
    user: 'int'
  }
};

realm = new Realm({
  schema: [Task]
});

Task["new"] = function(category, content, user) {
  return realm.write((function(_this) {
    return function() {
      var task;
      return task = realm.create('Task', {
        category: category,
        content: content,
        user: user,
        done: false,
        created: new Date(),
        modified: new Date()
      });
    };
  })(this));
};

Task.allTasks = function() {
  return realm.objects("Task");
};

exports.Task = Task;
